In [18]:
import numpy as np
import pandas as pd

In [2]:
a = np.ones((3, 3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [3]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [5]:
b=np.zeros((3, 3))

In [12]:
d=np.concatenate([a, b], axis=1)
print(d)

[[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]


In [15]:
d1,d2 = np.vsplit(d,[2])
print("d1 split")
print(d1)
print("d2 split")
print(d2)

d1 split
[[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]
d2 split
[[1. 1. 1. 0. 0. 0.]]


In [17]:
e=d.ndim
f=d.shape
g=d.size
print(e)
print(f)
print(g)


2
(3, 6)
18


In [19]:
ser1 = pd.Series([1,2,3,4],index = ['A', 'B', 'C', 'D'])
print(ser1)

A    1
B    2
C    3
D    4
dtype: int64


In [20]:
ser2 = pd.Series([11,22,55,44],index = ['A', 'B', 'E', 'D'])
print(ser2)

A    1
B    2
E    5
D    4
dtype: int64


In [23]:
df = pd.DataFrame({'A':ser1,'B':ser2})
df

A    B
A  1.0  1.0
B  2.0  2.0
C  3.0  NaN
D  4.0  4.0
E  NaN  5.0

In [39]:
pd.DataFrame(np.random.randn(5, 3), index=['a', 'c', 'e', 'f','h'],columns=['one', 'two', 'three'])

one       two     three
a -0.154295  1.783618  0.182985
c -0.248078 -0.857713 -1.396419
e -0.328628  0.647985 -1.828701
f -0.694116 -0.475899  0.084575
h -1.777059 -0.390116  1.688556

In [59]:
data = pd.read_csv('./k-means.csv')

In [52]:
data.head()

A0         A1        A2  y
0  2067.582042 -15.259519  0.020472  2
1  1319.589579 -18.412320  0.521308  0
2  1170.212183 -19.470602  0.814986  0
3  1424.162191   9.867841  0.848751  1
4  1551.069098  11.809364  0.884964  1

In [43]:
data.describe()

A0           A1           A2            y
count  1000.000000  1000.000000  1000.000000  1000.000000
mean   1489.096297    -7.166652     0.505010     0.999000
std     274.553828    13.077564     0.293416     0.817109
min     690.679955   -22.833984     0.000412     0.000000
25%    1295.382256   -17.161708     0.246973     0.000000
50%    1495.200642   -14.249017     0.518429     1.000000
75%    1676.991939     9.600518     0.766703     2.000000
max    2185.753771    17.595486     0.999833     2.000000